### Register User
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "test_user",
  "password": "password"
}

### Register User with same password
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "test_user1",
  "password": "password"
}

### Register User with "nikita" role
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "nikita",
  "password": "password"
}

### Register User with "admin" role
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}


### Register User with incorrect credentials
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "",
  "password": ""
}

### Sign User
POST http://localhost:3000/user/sign-in
Content-Type: application/json

{
  "username": "test_user",
  "password": "password"
}

### Sign User with same password
POST http://localhost:3000/user/sign-in
Content-Type: application/json

{
  "username": "test_user1",
  "password": "password"
}




