services:
  redis:
    container_name: redis_cache
    image: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    hostname: ${REDIS_HOST}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - redis:/data

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres:/data/postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    hostname: ${POSTGRES_HOST}
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  postgres:
    driver: bridge

volumes:
  redis:
    driver: local
  postgres:
  pgadmin: